[workspace]
resolver = "3"

[package]
name = "egui-dockspace-native-e2e"
version = "0.0.0"
edition = "2024"
rust-version = "1.92"
publish = false

[dependencies]
dockspace = { path = "../../crates/dockspace" }
eframe = { version = "=0.35.0", default-features = false, features = ["accesskit", "default_fonts", "glow", "native-test-support", "persistence", "wayland", "x11"] }
egui_dockspace = { path = "../../crates/egui_dockspace" }
egui_dockspace_native = { path = "../../crates/egui_dockspace_native" }

[patch.crates-io]
ecolor = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
eframe = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
egui = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
egui-wgpu = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
egui-winit = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
egui_glow = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
emath = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
epaint = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
epaint_default_fonts = { git = "https://github.com/Latias94/egui", rev = "e235606724964c26c280792c16a0e2e3c90c6acb" }
winit = { git = "https://github.com/Latias94/winit", rev = "ae4e6c5ee0af4b68c4ea1c2a2763b97e3ab7ae4c" }

[lints.rust]
unsafe_code = "forbid"
