[workspace]
resolver = "3"

[package]
name = "egui-dockspace-native-e2e"
version = "0.0.0"
edition = "2024"
rust-version = "1.92"
publish = false

[dependencies]
dockspace = { path = "../../crates/dockspace" }
eframe = { version = "=0.35.0", default-features = false, features = ["accesskit", "default_fonts", "glow", "native-test-support", "persistence", "wayland", "x11"] }
egui_dockspace = { path = "../../crates/egui_dockspace" }
egui_dockspace_native = { path = "../../crates/egui_dockspace_native" }

[patch.crates-io]
ecolor = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
eframe = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
egui = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
egui-wgpu = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
egui-winit = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
egui_glow = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
emath = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
epaint = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }
epaint_default_fonts = { git = "https://github.com/Latias94/egui", rev = "ebff89f25a3b84c51aa047a614eef3595f4e4c20" }

[lints.rust]
unsafe_code = "forbid"
