[workspace]
resolver = "3"
members = [
    "../../crates/egui_dockspace_native",
    "../egui-native-smoke",
]

[patch.crates-io]
ecolor = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
eframe = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
egui = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
egui-wgpu = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
egui-winit = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
egui_glow = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
emath = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
epaint = { git = "https://github.com/Latias94/egui", rev = "7f45a13771c85bebf0ad2f130e0bc02b41fd6f89" }
winit = { git = "https://github.com/Latias94/winit.git", rev = "23e8ddc6806a176c63efb80c998a2127faaf03cc" }
