[workspace]
resolver = "3"

[package]
name = "egui_dockspace_native"
description = "Unpublished fork-backed native runtime for egui_dockspace"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
authors = ["Mingzhen Zhuang <superfrankie621@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Latias94/egui_docking"
publish = false

[dependencies]
dockspace = { path = "../dockspace", default-features = false }
eframe = { version = "=0.35.0", default-features = false, features = ["accesskit", "default_fonts", "glow", "persistence", "wayland", "x11"] }
egui = { version = "=0.35.0", default-features = false }
egui_dockspace = { path = "../egui_dockspace", features = ["serde"] }
thiserror = "2.0.18"

[patch.crates-io]
ecolor = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
eframe = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
egui = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
egui-wgpu = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
egui-winit = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
egui_glow = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
emath = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
epaint = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
epaint_default_fonts = { git = "https://github.com/Latias94/egui", rev = "66920b0de76f84503145a3c8e0eabc0b65666413" }
winit = { git = "https://github.com/Latias94/winit", rev = "bc2d69433d733d113f7b0b507fe060d62f30b7d1" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"

[[example]]
name = "native_multiview"
path = "examples/native_multiview.rs"
