[workspace]
resolver = "3"

[package]
name = "egui-dockspace-fork-harness"
version = "0.0.0"
edition = "2024"
rust-version = "1.92"
publish = false

[dependencies]
eframe = { version = "=0.35.0", default-features = false, features = ["default_fonts", "glow", "wayland", "wgpu", "x11"] }
egui = { version = "=0.35.0", default-features = false, features = ["default_fonts"] }
egui_dockspace = { path = "../../crates/egui_dockspace" }
egui_dockspace_native = { path = "../../crates/egui_dockspace_native" }

[patch.crates-io]
ecolor = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
eframe = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
egui = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
egui-wgpu = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
egui-winit = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
egui_glow = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
emath = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
epaint = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }
epaint_default_fonts = { git = "https://github.com/Latias94/egui", rev = "3dc8c1b912516889a1312ec335a7bf3267555299" }

[lints.rust]
unsafe_code = "forbid"
